<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'QFGW' => 1,
        'QZZB' => 2,
        'QWXCB' => 3,
        'QJJJCW' => 4,
        'QWMB' => 5,
        'QWZFW' => 6,
        'QRMFY' => 7,
        'QJCY' => 8,
        'GAHXFJ' => 9,
        'QCZJ' => 10,
        'QKJJ' => 11,
        'QGZW' => 12,
        'QJYJ' => 13,
        'QSFJ' => 14,
        'QRLZYHSHBZJ' => 15,
        'QZJW' => 16,
        'QGSL' => 17,
        'QWLJ' => 18,
        'QSTHJJ' => 19,
        'QSWJ' => 20,
        'QHZJLB' => 21,
        'QMZJ' => 22,
        'QXWZX' => 23,
        'QWJW' => 24,
        'QYBJ' => 25,
        'QSWJ' => 26,
        'QTJJ' => 27,
        'QSCHZLJGJ' => 28,
        'QYJJ' => 29,
        'QJRJ' => 30,
        'QJGSWGLJ' => 31,
        'QWWXB' => 32,
        'QBB' => 33,
        'QSJJ' => 34,
        'GHHXFJ' => 35,
        'QCGW' => 36,
        'QTYJ' => 37,
        'QDAJ' => 38,
        'QZGH' => 39,
        'TQW' => 40,
        'QCL' => 41,
        'QMZB' => 42,
        'QGAJ' => 43,
        'QRFB' => 44,
        'QZSCQJ' => 45,
        'QWB' => 46,
        'QZFB' => 47,
        'QGHHZRZYJ' => 48
    );
}
